#!/bin/bash

cd "$(dirname "$0")"

sudo apt-get upgrade
sudo apt-get update
sudo chmod +x ./yzpi
sudo chown -R $USER:$USER .
sudo chmod -R u+w .

sudo apt-get install alsa-utils espeak python-full ffmprg

python3 -m venv venv
source venv/bin/activate
venv/bin/pip3 install -U pip wheel setuptools
venv/bin/pip3 install -r requirements.txt
deactivate

sudo cp ./yzpi /usr/bin/yzpi

if ! command -v python3 &> /dev/null
then
    echo "Ollama yükleniyor..."
    curl -fsSL https://ollama.com/install.sh | sh
    
    read -p "Gemma2 modelini indirmek istiyor musunuz? ([E]vet/[H]ayır): " tercih
    
    sudo systemctl enable ollama
    sudo systemctl start ollama
    
    if [[ "$tercih" == "E" || "$tercih" == "e" ]]
    then
        echo "Gemma2 modeli indiriliyor..."
        ollama pull gemma2
    else
        echo "Gemma2 modeli indirilmedi."
    fi
fi

echo "Kurulum tamamlandı